name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 코드 체크아웃
      - uses: actions/checkout@v3

      # Docker 로그인
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Docker 빌드
      - run: docker build -t devminii/react-test -f Dockerfile.dev .

      # Docker 컨테이너에서 테스트 실행
      - run: docker run -e CI=true devminii/react-test npm test

      # 배포 패키지 생성
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      # Elastic Beanstalk에 배포
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: react-docker-gh-test
          environment_name: React-docker-gh-test-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-709956054917
          region: ap-northeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
